version: '3.9'

services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        command: sleep infinity
        user: root
        volumes:
          - ./src:/app
        ports:
          - 8000:8000
        depends_on:
            - mysql
    mysql:
        image: mysql:8
        ports:
            - 5432:5432
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: myRootpwd32|
