# Generated by Django 4.0.1 on 2022-01-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='state',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
