# Generated by Django 4.0.1 on 2022-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options_rename_title_task_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('A', 'All'), ('B', 'In Progress'), ('C', 'Done'), ('D', 'Close')], default='A', max_length=10, verbose_name='State'),
        ),
    ]
