# Generated by Django 4.0.1 on 2022-02-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_state_alter_task_comments_alter_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('All', 'All'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Close', 'Close')], default='A', max_length=20, verbose_name='State'),
        ),
    ]
