# Generated by Django 4.0.1 on 2022-02-02 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_task_options_remove_task_date_task_expiredate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['expire_date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='expiredate',
            new_name='expire_date',
        ),
        migrations.AddField(
            model_name='task',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
