# Generated by Django 4.0.2 on 2022-02-03 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_task_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
